# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Start projects

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Ruby
      uses: actions/setup-ruby@v1
    - run: ruby main.rb
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
